# Generated by Django 5.0 on 2025-08-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_projectsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsdetails',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Mainapp.project'),
            preserve_default=False,
        ),
    ]
