# Generated by Django 5.2.1 on 2025-06-08 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default=django.utils.timezone.now, help_text='Comma-separated tags (e.g. Django, Tailwind, JavaScript)', max_length=300),
            preserve_default=False,
        ),
    ]
